### ISSUE TITLE
MIT License?

### ISSUE THREAD

**Issue by Coda-Coda** [CertiCoq/VeriFFI#7]
Hi,

This looks really interesting!

I understand CertiCoq is open source and distributed under the [MIT license](https://github.com/CertiCoq/certicoq/blob/master/LICENSE.md) as stated in the [CertiCoq repo](https://github.com/CertiCoq/certicoq) and that VeriFFI is "part of [the] CertiCoq project". Does that mean that this VeriFFI repository is also under the MIT license? If so, it would be helpful if an appropriate `LICENSE.md` file was added here too.

Thanks :)

**Comment by joom** [comment]
Thanks for your interest! Added MIT license.

**Comment by Coda-Coda** [comment]
Great, thanks 😃
